### ISSUE TITLE
Localizations added to localizations folder can't be installed

### ISSUE THREAD

**Issue by takoyaro** [h0useRus/StarCitizen#33]
Upon adding my localizations to the `localizations/` folder, I can't install them.
I tried dropping the files in the `localizations/` folder as well as `localizatons/[language]` folder and adding those from the **Manage** window without success.

SC Tools keeps on showing me 
![image](https://user-images.githubusercontent.com/54836677/180907002-587ad318-d847-4130-b35c-57cb012376ea.png)
![image](https://user-images.githubusercontent.com/54836677/180907049-85cac41d-640b-418b-948e-d0f7e959ee30.png)

**Comment by takoyaro** [comment]
I'm not sure what I'm doing wrong but even localization from [my own repo](https://github.com/takoyaro/scjp) doesn't seem to work:
![image](https://user-images.githubusercontent.com/54836677/180922325-72ff00a9-5070-4b30-976e-6b5550953900.png)

**Comment by defterai** [comment]
You should put archive with localization directly inside localizations/ folder instead unpacked files from it
